export const disableNavbarWithFooter = [
  "/sign-in",
  "/register",
  "/dashboard",
  "/dashboard/products",
  "/dashboard/products/create",
  "/dashboard/banners",
  "/dashboard/banners/create",
  "/help",
  "/help/contact",
  "/help/privacy-policy",
  "/help/term-of-services",
  "/help/term-of-use",
  "/help/faqs",
]
